# Tomcat Server Setting
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true

# SpringBoot Environment Setting
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

# MyBatis Setting
mybatis:
  type-aliases-package: edu.sunmoon.app.dto
  mapper-locations: classpath:/mapper/*.xml

# Logging Setting
logging:
  level:
    root: info

# Application Environment Setting
app:
  dir:
    images: file:///Users/yeonkyun/IdeaProjects/spring-smu/images/
    uploadimgdir: /Users/yeonkyun/IdeaProjects/spring-smu/images/
    logs: file:///Users/yeonkyun/IdeaProjects/spring-smu/logs/
    readlogdir: /Users/yeonkyun/IdeaProjects/spring-smu/logs/
  key:
    wkey: ENC(QdOsjLohLq1MPwpHZYB9hMyr+NY0bXXyORg1vRQEnmXS59mZAkg+vRNof9FFPDLTkMZLaMkMQ9NHNu8bI2/ZJQFb304B3s/MIJnouj5n9u9qUhyp2smp4mXRaqQz3KdpVmVZZSxLehC6Le73m78zGA==)
    wkey2: ENC(AGzLAgsPMOJE5zDYsXEricMGvjB/S1GVF2ZFRTuO9qjnlj/sMv6d/xF0pAuzWJkn)
    algo: PBEWithMD5AndDES
    skey: mykey